### ISSUE TITLE
How many N.m do we need for 350mm?

### ISSUE THREAD

**Issue by pasha4ur** [MathematicalPotato/Voron_Mods#1]
Hello

Thank you for this mod.

How many N.m do we need for 350 mm with standard thickness?

You wrote:
> try to get Z motors that have at least 0.2 mNm of detent torque

For example 40 mm motor (I have this):

Cloudray Nema 17 Stepper Motor  40mm 0.42 N.m 1.7A 2 Phase 
https://ae01.alicdn.com/kf/Heec5ff7f53b0446ba1fe4dcbd27f9fbbB.jpg
https://www.aliexpress.com/item/1005001303445983.html

or 60 mm:

Nema17 Stepper Motor 60mm 2 Phase 71 N.m 1.8A Stepper Motor 
https://www.aliexpress.com/item/4000934544704.html

I'm building Trident with build volume 450 mm. But for this moment I have standard 350 mm build plate.

**Comment by MathematicalPotato** [comment]
You're looking for the detent torque rating of the steppers not the holding torque.  Holding torque is how much torque it takes to turn the motor shaft when powered on and running at the rated current.  Detent torque is the amount of torque it takes to turn the shaft when no power is applied.  For beds, we are more interested in the detent torque rating as if this value is not spec'd high enough compared to the Z axis moving mass, the bed will drop on power off.  This can break components depending on the weight of the bed or fry electronics if the steppers back feed into the controller board.

For reference, a torque rating of 1Nm with a 16T/20T pulley on the motor shaft and 1:1 gearing should hold about 40lbs per motor.  This reference value is higher than the powered (holding) torque rating of pretty much every NEMA17 stepper targeted at 3DP.  For steppers that do not have data sheets or that do not have detent torque listed on the data sheets I would either compare to a comparable LDO model or assume detent torque is somewhere around 2-4% of the holding torque.  It can also be measured using an arm of a known length bolted to the motor and pushing that shaft against a kitchen scale and recording the maximum mass.  It takes some math to get back to detent torque, but it's a good method if there isn't any other data.

The 60mm long NEMA17s seem to have the highest detent torque available, but they still top out around 0.030Nm of detent torque.  This value should be able to hold about 3.7lbs per motor without power on 5:1 gearing.  My belted Z design uses 3 drives which would only be able to hold an absolute maximum of ~11.1lbs with these motors.  Based on some quick math, I estimate a 9mm thick 350mm bed assembly (with bed mounts, extrusions, etc) for a Trident would weight approximately 13lbs.  This also doesn't account for print mass.  With these values, I would not recommend running 5:1 belted Z for machines larger than 300mm.  

I would recommend looking into worm gear Z drives similar to the style used on the Z axis of the Annex Engineering K1/K2 and Redoubt as they can provide significantly higher gear reductions.  A minimum of 10:1 gearing would be ideal for your machine size.
