### ISSUE TITLE
Can you make it compatible with Idex's idlers?

### ISSUE THREAD

**Issue by pasha4ur** [MathematicalPotato/Voron_Mods#2]
Hello.

With belted Z and Idex trident can shine with more power. )

https://github.com/FrankenVoron/Tridex/blob/main/Documentation/Assembly_Manual_Tridex_Front_Idler.pdf

**Comment by MathematicalPotato** [comment]
This should be possible with the existing parts, but would likely require shorter Z rails, taller bed standoffs, and a reduced Z travel compared to a stock machine in the same frame size.  It is outside the scope of this mod, but a lot of the design elements could be reused.
